# Generated by Django 4.1.5 on 2023-01-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(max_length=10)),
                ('fname', models.CharField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.users')),
            ],
        ),
    ]
