# Generated by Django 4.1.5 on 2023-01-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='rollno',
        ),
    ]
