# Generated by Django 4.1.5 on 2023-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_details_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='rollno',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
