# Generated by Django 4.1.5 on 2023-01-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_details_rollno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User_details',
        ),
    ]
