# Generated by Django 4.1.5 on 2023-01-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_users_user_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='User_details',
            new_name='User_detail',
        ),
    ]
