# Generated by Django 4.1.5 on 2023-04-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('ctc_min', models.PositiveIntegerField()),
                ('ctc_max', models.PositiveIntegerField()),
                ('other_info', models.TextField(blank=True)),
                ('comp_link', models.TextField()),
                ('drive_strt_date', models.DateField()),
                ('drive_end_date', models.DateField()),
                ('required_skill', models.TextField(blank=True)),
                ('job_desc', models.TextField()),
                ('last_reg_date', models.DateField()),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
                ('eligible_10th_minp', models.PositiveSmallIntegerField()),
                ('eligible_12th_minp', models.PositiveSmallIntegerField()),
                ('type_of_offer', models.CharField(default='nil', max_length=25)),
                ('hist_of_arr', models.CharField(max_length=25)),
                ('admin_approval', models.CharField(blank=True, default='review', max_length=30)),
                ('status_of_drive', models.CharField(blank=True, default='active', max_length=100)),
            ],
        ),
    ]
