# Generated by Django 4.1.5 on 2023-04-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='eligible_ug_minp',
            field=models.DecimalField(blank=True, decimal_places=2, default=8.5, max_digits=4),
            preserve_default=False,
        ),
    ]
